### ISSUE TITLE
Will you offer the code for "Equivariant Symmetries for Inertial Navigation Systems" soon?

### ISSUE THREAD

**Issue by hqtang-git** [aau-cns/ABC-EqF#1]
Will you offer the code for "Equivariant Symmetries for Inertial Navigation Systems" soon?

**Comment by AlessandroFornasier** [comment]
Hi! We’re happy to see interest in our research.

at the moment we are not planning to release a full implementation for each filter discussed, however, we planned to release a C++ implementation of a small library that implements the symmetry group to bootstrap the development of EqFs.

Soon we will be also releasing also a real-time C++ implementation of an EqF for the VIO problem that is related to another project, stay tuned.

**Comment by hqtang-git** [comment]
Thank you for your great works. I believe that any material you provide will contribute to the development of EqF

**Comment by hqtang-git** [comment]
> Hi! We’re happy to see interest in our research.
> 
> at the moment we are not planning to release a full implementation for each filter discussed, however, we planned to release a C++ implementation of a small library that implements the symmetry group to bootstrap the development of EqFs.
> 
> Soon we will be also releasing also a real-time C++ implementation of an EqF for the VIO problem that is related to another project, stay tuned.

Thank you for your work. I believe that any material you provide will contribute to the development of EqF！！

**Comment by AlessandroFornasier** [comment]
Here https://github.com/aau-cns/Lie-plusplus the C++ header-only library that implements the group discussed in "Equivariant Symmetries for Inertial Navigation Systems"
