### ISSUE TITLE
Code is not running due to a pylie module error

### ISSUE THREAD

**Issue by piergo98** [aau-cns/ABC-EqF#2]
Unfortunatey, i tired many times and following different procedures to install the package pylie, but it seems not to work. I always get the following error: 
"Traceback (most recent call last):
  File "/home/pietro/ABC-EqF/examples/simulation.py", line 30, in <module>
    from pylie import SO3
ModuleNotFoundError: No module named 'pylie'".

I hope you can help me.

**Comment by AlessandroFornasier** [comment]
Hi, thanks for the interested in our work.

would you mind telling me the operating system and the environment you are trying to run the code in?

**Comment by piergo98** [comment]
I'm currently working on Ubuntu 22.10, and I'm using the basic Python 3.10 environment, without any virtualenv.

**Comment by AlessandroFornasier** [comment]
Hi,

pylie got recently updated. Here is how to install it.

```
python3 -m pip install --upgrade build
git clone https://github.com/pvangoor/pylie.git
cd pylie
python3 -m build && python3 -m pip install dist/pylie-0.1.0.tar.gz
```

Please let me know if this work. I will update the readme accordingly.

**Comment by piergo98** [comment]
Yes, now it's working. Thank you very much.
